# Generated by Django 3.2.4 on 2021-08-07 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 19, 6, 31, 683110)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(default=None, verbose_name='Post Content'),
        ),
    ]
