# Generated by Django 3.2.4 on 2021-08-07 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210807_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 22, 33, 25, 140978)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(default=None, verbose_name='New Post'),
        ),
    ]
