# Generated by Django 3.2.4 on 2021-08-09 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210809_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 6, 21, 26, 873720)),
        ),
    ]
